### ISSUE TITLE
ubuntu-serv hosts fails due to missing python

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-ansible#16]
Looks like this needs a bootstrap playbook to allow installation on a vanilla 16.04 server.

```
fatal: [distleech.wuvt.vt.edu]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "\r\n/bin/sh: 1: /usr/bin/python: not found\r\n", "msg": "MODULE FAILURE", "parsed": false}
```

**Comment by echarlie** [comment]
known issue: resolved wontfix

**Comment by echarlie** [comment]
well, to fix this, run ansible with python3 as your interpreter: 
https://docs.ansible.com/ansible/latest/python_3_support.html
