### ISSUE TITLE
Support for Ubuntu Studio machines

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-ansible#3]
At the very least we must support US 14.04 LTS with:
- LDAP auth (use a host var to determine which LDAP group user must be in to login)
- NFS home directories
- SSH server
- Installation of common software
- Focusrite 2i2 USB sound devices (future)
- Mounting network shares (CIFS)
- Printer configuration
- Audio out via headphone jack on iMacs

**Comment by echarlie** [comment]
Most of these features have been met, and we are moving to the 16.04 LTS in the next few months.
- LDAP is *mostly* fuctional, although kerberos would be nice
- NFS works
- SSH works as part of ansible requirements
- Common software done
- 2i2 is mostly supported out-of-box.
- CIFS is dead
- CUPS role added
- Audio works, last I checked
